### ISSUE TITLE
putting SUSY-Map partner on the map

### ISSUE THREAD

**Issue by josefkreitmayer** [susy-mapviewer/transformap-viewer#12]
@species 
we can now put all SSEDAS partner´s location on the map.

The filte is named "SSEDAS partner_geocoded_for_mapintegration.ods".
It can be found in /projects/ssedas/ssedas partners/

The file is structured as the other import templates, and the relevant tags "ssedas_partner" are set. 
The only difference to the original template: lat and lon are in one column (named "longitude (X)") and not in 2 separate ones.

**Comment by species** [comment]
there is no such file.
Are you sure you uploaded it to our OwnCloud?

**Comment by josef-legacy-account** [comment]
@species, need to apologize,

as my owncloud client did not sync anymore, I uninstalled it, and need to install it. 

File is now sent via email.
sry for the quick fix.

**Comment by species** [comment]
added in conjunction with IT data.
