### ISSUE TITLE
implement "other" icon

### ISSUE THREAD

**Issue by josefkreitmayer** [susy-mapviewer/transformap-viewer#13]
@species the icon for the tag "other" can be found here: 
https://github.com/susy-mapviewer/transformap-viewer/blob/gh-pages/assets/turquoise_other.png

Thank you for implementation. 
I will test, once you notify me.
----
The following might be irrelevant for this issue. Once the icon is implemented, we will see, if it is relevant, if not, we can make it a minor issue. 

In the popup, there seem to be 3 types of other:
- other
- Other
- Other (open category)

**Comment by josef-legacy-account** [comment]
great, tested it, done!

**Comment by species** [comment]
fixed by updating the taxonomy from the Wikbase into RDF export.
